version: "3.9"

services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: note_sql_server
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "YayaNetPassw0rd"
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql

  backend:
    build: ./backend
    container_name: note_api
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ConnectionStrings__DefaultConnection: "Server=db;Database=NoteDb;User Id=sa;Password=YayaNetPassw0rd;TrustServerCertificate=True"

  frontend:
    build: ./frontend
    container_name: note_frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
    environment:
      VITE_API_URL: "http://localhost:8080/api"
    command: ["npm", "run", "dev", "--", "--host", "0.0.0.0"]

volumes:
  sql_data:
